/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArrendamientosRouteImport } from './routes/arrendamientos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as GastronomiaRouteImport } from './routes/gastronomia'
import { Route as PromocionesRouteImport } from './routes/promociones'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as VisitanosRouteImport } from './routes/visitanos'
import { Route as DirectorioIndexRouteImport } from './routes/directorio.index'
import { Route as DirectorioSlugRouteImport } from './routes/directorio.$slug'
import { Route as EventosIndexRouteImport } from './routes/eventos.index'
import { Route as EventosSlugRouteImport } from './routes/eventos.$slug'
import { Route as NovedadesIndexRouteImport } from './routes/novedades.index'
import { Route as NovedadesSlugRouteImport } from './routes/novedades.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrendamientosRoute = ArrendamientosRouteImport.update({
  id: '/arrendamientos',
  path: '/arrendamientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const GastronomiaRoute = GastronomiaRouteImport.update({
  id: '/gastronomia',
  path: '/gastronomia',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocionesRoute = PromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitanosRoute = VisitanosRouteImport.update({
  id: '/visitanos',
  path: '/visitanos',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioIndexRoute = DirectorioIndexRouteImport.update({
  id: '/directorio/',
  path: '/directorio/',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectorioSlugRoute = DirectorioSlugRouteImport.update({
  id: '/directorio/$slug',
  path: '/directorio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosIndexRoute = EventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosSlugRoute = EventosSlugRouteImport.update({
  id: '/eventos/$slug',
  path: '/eventos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesIndexRoute = NovedadesIndexRouteImport.update({
  id: '/novedades/',
  path: '/novedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesSlugRoute = NovedadesSlugRouteImport.update({
  id: '/novedades/$slug',
  path: '/novedades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrendamientos': typeof ArrendamientosRoute
  '/contacto': typeof ContactoRoute
  '/gastronomia': typeof GastronomiaRoute
  '/promociones': typeof PromocionesRoute
  '/servicios': typeof ServiciosRoute
  '/visitanos': typeof VisitanosRoute
  '/directorio/$slug': typeof DirectorioSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/novedades/$slug': typeof NovedadesSlugRoute
  '/directorio/': typeof DirectorioIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/novedades/': typeof NovedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrendamientos': typeof ArrendamientosRoute
  '/contacto': typeof ContactoRoute
  '/gastronomia': typeof GastronomiaRoute
  '/promociones': typeof PromocionesRoute
  '/servicios': typeof ServiciosRoute
  '/visitanos': typeof VisitanosRoute
  '/directorio/$slug': typeof DirectorioSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/novedades/$slug': typeof NovedadesSlugRoute
  '/directorio': typeof DirectorioIndexRoute
  '/eventos': typeof EventosIndexRoute
  '/novedades': typeof NovedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrendamientos': typeof ArrendamientosRoute
  '/contacto': typeof ContactoRoute
  '/gastronomia': typeof GastronomiaRoute
  '/promociones': typeof PromocionesRoute
  '/servicios': typeof ServiciosRoute
  '/visitanos': typeof VisitanosRoute
  '/directorio/$slug': typeof DirectorioSlugRoute
  '/eventos/$slug': typeof EventosSlugRoute
  '/novedades/$slug': typeof NovedadesSlugRoute
  '/directorio/': typeof DirectorioIndexRoute
  '/eventos/': typeof EventosIndexRoute
  '/novedades/': typeof NovedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrendamientos'
    | '/contacto'
    | '/gastronomia'
    | '/promociones'
    | '/servicios'
    | '/visitanos'
    | '/directorio/$slug'
    | '/eventos/$slug'
    | '/novedades/$slug'
    | '/directorio/'
    | '/eventos/'
    | '/novedades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrendamientos'
    | '/contacto'
    | '/gastronomia'
    | '/promociones'
    | '/servicios'
    | '/visitanos'
    | '/directorio/$slug'
    | '/eventos/$slug'
    | '/novedades/$slug'
    | '/directorio'
    | '/eventos'
    | '/novedades'
  id:
    | '__root__'
    | '/'
    | '/arrendamientos'
    | '/contacto'
    | '/gastronomia'
    | '/promociones'
    | '/servicios'
    | '/visitanos'
    | '/directorio/$slug'
    | '/eventos/$slug'
    | '/novedades/$slug'
    | '/directorio/'
    | '/eventos/'
    | '/novedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrendamientosRoute: typeof ArrendamientosRoute
  ContactoRoute: typeof ContactoRoute
  GastronomiaRoute: typeof GastronomiaRoute
  PromocionesRoute: typeof PromocionesRoute
  ServiciosRoute: typeof ServiciosRoute
  VisitanosRoute: typeof VisitanosRoute
  DirectorioSlugRoute: typeof DirectorioSlugRoute
  EventosSlugRoute: typeof EventosSlugRoute
  NovedadesSlugRoute: typeof NovedadesSlugRoute
  DirectorioIndexRoute: typeof DirectorioIndexRoute
  EventosIndexRoute: typeof EventosIndexRoute
  NovedadesIndexRoute: typeof NovedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrendamientos': {
      id: '/arrendamientos'
      path: '/arrendamientos'
      fullPath: '/arrendamientos'
      preLoaderRoute: typeof ArrendamientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastronomia': {
      id: '/gastronomia'
      path: '/gastronomia'
      fullPath: '/gastronomia'
      preLoaderRoute: typeof GastronomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promociones': {
      id: '/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof PromocionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitanos': {
      id: '/visitanos'
      path: '/visitanos'
      fullPath: '/visitanos'
      preLoaderRoute: typeof VisitanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio/': {
      id: '/directorio/'
      path: '/directorio'
      fullPath: '/directorio/'
      preLoaderRoute: typeof DirectorioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directorio/$slug': {
      id: '/directorio/$slug'
      path: '/directorio/$slug'
      fullPath: '/directorio/$slug'
      preLoaderRoute: typeof DirectorioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/': {
      id: '/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof EventosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos/$slug': {
      id: '/eventos/$slug'
      path: '/eventos/$slug'
      fullPath: '/eventos/$slug'
      preLoaderRoute: typeof EventosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades/': {
      id: '/novedades/'
      path: '/novedades'
      fullPath: '/novedades/'
      preLoaderRoute: typeof NovedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades/$slug': {
      id: '/novedades/$slug'
      path: '/novedades/$slug'
      fullPath: '/novedades/$slug'
      preLoaderRoute: typeof NovedadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrendamientosRoute: ArrendamientosRoute,
  ContactoRoute: ContactoRoute,
  GastronomiaRoute: GastronomiaRoute,
  PromocionesRoute: PromocionesRoute,
  ServiciosRoute: ServiciosRoute,
  VisitanosRoute: VisitanosRoute,
  DirectorioSlugRoute: DirectorioSlugRoute,
  EventosSlugRoute: EventosSlugRoute,
  NovedadesSlugRoute: NovedadesSlugRoute,
  DirectorioIndexRoute: DirectorioIndexRoute,
  EventosIndexRoute: EventosIndexRoute,
  NovedadesIndexRoute: NovedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
