/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArrendamientosRouteImport } from './routes/arrendamientos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as GastronomiaRouteImport } from './routes/gastronomia'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PromocionesRouteImport } from './routes/promociones'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as VisitanosRouteImport } from './routes/visitanos'
import { Route as ComerciosIndexRouteImport } from './routes/comercios.index'
import { Route as ComerciosSlugRouteImport } from './routes/comercios.$slug'
import { Route as NovedadesIndexRouteImport } from './routes/novedades.index'
import { Route as NovedadesSlugRouteImport } from './routes/novedades.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrendamientosRoute = ArrendamientosRouteImport.update({
  id: '/arrendamientos',
  path: '/arrendamientos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const GastronomiaRoute = GastronomiaRouteImport.update({
  id: '/gastronomia',
  path: '/gastronomia',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocionesRoute = PromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitanosRoute = VisitanosRouteImport.update({
  id: '/visitanos',
  path: '/visitanos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerciosIndexRoute = ComerciosIndexRouteImport.update({
  id: '/comercios/',
  path: '/comercios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComerciosSlugRoute = ComerciosSlugRouteImport.update({
  id: '/comercios/$slug',
  path: '/comercios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesIndexRoute = NovedadesIndexRouteImport.update({
  id: '/novedades/',
  path: '/novedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesSlugRoute = NovedadesSlugRouteImport.update({
  id: '/novedades/$slug',
  path: '/novedades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrendamientos': typeof ArrendamientosRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/gastronomia': typeof GastronomiaRoute
  '/privacidad': typeof PrivacidadRoute
  '/promociones': typeof PromocionesRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/visitanos': typeof VisitanosRoute
  '/comercios/$slug': typeof ComerciosSlugRoute
  '/novedades/$slug': typeof NovedadesSlugRoute
  '/comercios/': typeof ComerciosIndexRoute
  '/novedades/': typeof NovedadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrendamientos': typeof ArrendamientosRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/gastronomia': typeof GastronomiaRoute
  '/privacidad': typeof PrivacidadRoute
  '/promociones': typeof PromocionesRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/visitanos': typeof VisitanosRoute
  '/comercios/$slug': typeof ComerciosSlugRoute
  '/novedades/$slug': typeof NovedadesSlugRoute
  '/comercios': typeof ComerciosIndexRoute
  '/novedades': typeof NovedadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrendamientos': typeof ArrendamientosRoute
  '/contacto': typeof ContactoRoute
  '/eventos': typeof EventosRoute
  '/gastronomia': typeof GastronomiaRoute
  '/privacidad': typeof PrivacidadRoute
  '/promociones': typeof PromocionesRoute
  '/servicios': typeof ServiciosRoute
  '/terminos': typeof TerminosRoute
  '/visitanos': typeof VisitanosRoute
  '/comercios/$slug': typeof ComerciosSlugRoute
  '/novedades/$slug': typeof NovedadesSlugRoute
  '/comercios/': typeof ComerciosIndexRoute
  '/novedades/': typeof NovedadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrendamientos'
    | '/contacto'
    | '/eventos'
    | '/gastronomia'
    | '/privacidad'
    | '/promociones'
    | '/servicios'
    | '/terminos'
    | '/visitanos'
    | '/comercios/$slug'
    | '/novedades/$slug'
    | '/comercios/'
    | '/novedades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrendamientos'
    | '/contacto'
    | '/eventos'
    | '/gastronomia'
    | '/privacidad'
    | '/promociones'
    | '/servicios'
    | '/terminos'
    | '/visitanos'
    | '/comercios/$slug'
    | '/novedades/$slug'
    | '/comercios'
    | '/novedades'
  id:
    | '__root__'
    | '/'
    | '/arrendamientos'
    | '/contacto'
    | '/eventos'
    | '/gastronomia'
    | '/privacidad'
    | '/promociones'
    | '/servicios'
    | '/terminos'
    | '/visitanos'
    | '/comercios/$slug'
    | '/novedades/$slug'
    | '/comercios/'
    | '/novedades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrendamientosRoute: typeof ArrendamientosRoute
  ContactoRoute: typeof ContactoRoute
  EventosRoute: typeof EventosRoute
  GastronomiaRoute: typeof GastronomiaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  PromocionesRoute: typeof PromocionesRoute
  ServiciosRoute: typeof ServiciosRoute
  TerminosRoute: typeof TerminosRoute
  VisitanosRoute: typeof VisitanosRoute
  ComerciosSlugRoute: typeof ComerciosSlugRoute
  NovedadesSlugRoute: typeof NovedadesSlugRoute
  ComerciosIndexRoute: typeof ComerciosIndexRoute
  NovedadesIndexRoute: typeof NovedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrendamientos': {
      id: '/arrendamientos'
      path: '/arrendamientos'
      fullPath: '/arrendamientos'
      preLoaderRoute: typeof ArrendamientosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gastronomia': {
      id: '/gastronomia'
      path: '/gastronomia'
      fullPath: '/gastronomia'
      preLoaderRoute: typeof GastronomiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promociones': {
      id: '/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof PromocionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitanos': {
      id: '/visitanos'
      path: '/visitanos'
      fullPath: '/visitanos'
      preLoaderRoute: typeof VisitanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercios/': {
      id: '/comercios/'
      path: '/comercios'
      fullPath: '/comercios/'
      preLoaderRoute: typeof ComerciosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercios/$slug': {
      id: '/comercios/$slug'
      path: '/comercios/$slug'
      fullPath: '/comercios/$slug'
      preLoaderRoute: typeof ComerciosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades/': {
      id: '/novedades/'
      path: '/novedades'
      fullPath: '/novedades/'
      preLoaderRoute: typeof NovedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades/$slug': {
      id: '/novedades/$slug'
      path: '/novedades/$slug'
      fullPath: '/novedades/$slug'
      preLoaderRoute: typeof NovedadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrendamientosRoute: ArrendamientosRoute,
  ContactoRoute: ContactoRoute,
  EventosRoute: EventosRoute,
  GastronomiaRoute: GastronomiaRoute,
  PrivacidadRoute: PrivacidadRoute,
  PromocionesRoute: PromocionesRoute,
  ServiciosRoute: ServiciosRoute,
  TerminosRoute: TerminosRoute,
  VisitanosRoute: VisitanosRoute,
  ComerciosSlugRoute: ComerciosSlugRoute,
  NovedadesSlugRoute: NovedadesSlugRoute,
  ComerciosIndexRoute: ComerciosIndexRoute,
  NovedadesIndexRoute: NovedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
